feat: task 121 - creating variables in styled components
squadroxo/sr.dentech pull request #34
Opened 2024-10-30 12:16 UTC by camillamendess

2024-10-30 22:20 UTC, lucasbapDEV requested changes

2024-10-30 22:20 UTC, lucasbapDEV commented on src/styles/theme.ts
> +    primary: "'Inter', sans-serif",
Comentário de teste

2024-10-31 13:44 UTC, zingarelli commented on src/styles/GlobalStyles.ts
> +    font-family: 'Inter', sans-serif;
Acho que aqui pode usar a propriedade que tá no theme:

`font-family: ${({ theme }) => theme.fonts.primary};`

2024-10-31 13:48 UTC, zingarelli commented on src/index.tsx
>  import './index.scss';
esse arquivo tem vários outros estilos globais. Uma sugestão seria copiar tudo o que tá aqui para o GlobalStyles.ts e ajustar com as variáveis criadas no theme.ts, daí futuramente apagar esse index.scss. Não sei se vale fazer isso já ou mais pra frente.

2024-10-31 14:57 UTC, zingarelli approved these changes

2024-10-31 19:40 UTC, lucasbapDEV approved these changes

2024-10-31 20:01 UTC, merged