feat: creating section and carousel template
squadroxo/sr.dentech pull request #35
Opened 2024-11-01 17:25 UTC by camillamendess

Tasks: 
115 - https://srdente.atlassian.net/browse/SCRUM-115
116 - https://srdente.atlassian.net/browse/SCRUM-116
117 - https://srdente.atlassian.net/browse/SCRUM-117
118 - https://srdente.atlassian.net/browse/SCRUM-118

2024-11-06 15:26 UTC, zingarelli requested changes
Tem duas questões visuais que eu não sei o quão "rígido" devemos ser em relação ao Figma:

- Os cards parecem ter um limite de 4 linhas (ou um height fixo) e depois disso o texto é truncado e adicionam "...". Não sei se isso seria necessário ser implementado ou se é uma questão visual irrelevante.

- O carrossel ficou diferente do Figma: tem botões de navegação e somente 1 card é mostrado por vez.

2024-11-06 15:26 UTC, zingarelli commented on src/components/ContainerSection/style.ts
> +`;
acho que seria bom adicionar uma media query para não mostrar esse conteúdo na versão desktop

2024-11-06 15:26 UTC, zingarelli commented on src/styles/styled.d.ts
> +            azul_claro: string;
vamos manter o nome de variáveis em inglês ou tanto faz?

2024-11-06 15:26 UTC, zingarelli commented on src/styles/theme.ts
> +    azul_claro: '#D6FDFF',
vamos manter o nome de variáveis em inglês ou tanto faz?

2024-11-06 15:26 UTC, zingarelli commented on src/components/ContainerSection/style.ts
> +  .container__card__title {
No Figma estão usando outra fonte para os cards, tanto para o título como para os textos: Lato

https://fonts.google.com/specimen/Lato

2024-11-06 15:26 UTC, zingarelli commented on src/components/Carousel/style.ts
> +    font-size: 14px;
No Figma estão usando outra fonte para os cards, tanto para o título como para os textos: Lato

https://fonts.google.com/specimen/Lato

2024-11-06 16:46 UTC, camillamendess commented on src/styles/theme.ts
> +    azul_claro: '#D6FDFF',
Acho melhor...

2024-11-07 14:32 UTC, zingarelli approved these changes

2024-11-07 15:10 UTC, merged