feat: task 120
squadroxo/sr.dentech pull request #36
Opened 2024-11-01 19:52 UTC by zingarelli

https://srdente.atlassian.net/browse/SCRUM-120

Deixei uma anotação para futuramente apagar o componente ContainerButton e substituí-lo nos outros componentes por esse novo Button criado. Acredito que deve ser feito na história da Reconfiguração da Home [Web], para evitar conflitos no código.

2024-11-02 00:11 UTC, camillamendess requested changes

2024-11-02 00:11 UTC, camillamendess commented on src/components/Button/index.tsx
> +      <Styles.Button
O certo seria que o Elemento `<a>` ficasse dentro do `<button>`, pois o cursor está reconhecendo como link fora do elemento do botão.

Seria: 
  ```
    <Styles.Button
        onClick={onClick}
        disabled={disabled}
        className={className}
        $secondary={secondary}
      >
        <Styles.ButtonLink href={link} target={target}>
          <Styles.Label
            className={labelClassName}
            $secondary={secondary}
          >
            {label}
          </Styles.Label>
        </Styles.ButtonLink>
      </Styles.Button>
```

2024-11-02 00:11 UTC, camillamendess commented on src/components/Button/styles.ts
> +
No Figma possui uma cor pra pressed, aqui poderia adicionar um estilo para isso, exemplo para a o botão primário: 
```
  &:active {
    background-color: #006361; 
  }
```
E essas cores de pressed não estão nas variáveis, seria interessante já adicioná-las no theme.ts.

2024-11-02 00:11 UTC, camillamendess commented on src/components/Button/styles.ts
> +}
Aqui poderia adicionar um boolean para disabled, caso o botão passar disabled como true, adiciona os estilos de um botão disabled que tem no Figma e desativar o cursor, tipo `cursor: ${({ $disabled }) => $disabled ? 'not-allowed' : 'pointer'};`

2024-11-04 13:48 UTC, zingarelli commented on src/components/Button/styles.ts
> +
Estou em dúvida com relação ao Figma. Dando uma olhada, encontrei dois lugares em que as cores para os botões são definidas. Em uma, o pressed está com as cores: #006361 (tema verde) e #702661 (tema roxo); em outra, é a cor #053538 (somente tema verde, tem um terceiro tema nela é que preto). 

As cores para hover e disabled também são diferentes - inclusive, as cores já existentes no código para hover não são as mesmas do Figma. 

E agora?

2024-11-04 19:46 UTC, camillamendess approved these changes

2024-11-04 20:06 UTC, merged