132 cards web
squadroxo/sr.dentech pull request #40
Opened 2024-11-14 11:51 UTC by camillamendess

https://srdente.atlassian.net/browse/SCRUM-132

Adicionei comentários para melhor entendimento da lógica criada, irei tirá-los antes do merge.

2024-11-14 14:51 UTC, zingarelli requested changes
Acho melhor aguardar se a largura da media-query será alterada e qual vai ser o tamanho.

2024-11-14 14:51 UTC, zingarelli commented on src/components/ContainerSection/index.tsx
> +        className={`container__card__content ${isDesktop && (isEven ? "image-left" : "image-right") // Alterna apenas no desktop
As classes "image-left" e "image-right" não estão sendo usadas no CSS, então acho que essa lógica pode ser eliminada. As linhas seguintes estão tratando via JS de que lado a imagem deve aparecer.

2024-11-14 14:51 UTC, zingarelli commented on src/components/ContainerSection/index.tsx
> +        <Button
Por enquanto, o botão vai para uma página em construção (rota "/construcao") e sem abrir nova aba (sem a prop target).

Futuramente, é provável que a gente tenha que alterar esse componente para receber o link de algum outro jeito, pois cada seção vai ter uma rota diferente para sua própria página.

2024-11-15 14:23 UTC, camillamendess commented on src/components/ContainerSection/index.tsx
> +        <Button
Sim, talvez seja uma boa colocar o link como uma prop e cada seção terá seu link.

2024-11-18 13:31 UTC, zingarelli approved these changes

2024-11-18 22:12 UTC, merged